### ISSUE TITLE
μs != ms 

### ISSUE THREAD

**Issue by lejibxl** [MrYsLab/pymata-express#39]
In the documentation we speak of milliseconds while we should speak of microseconds. 
How to have 540ms in a cycle of 20ms (50Hz) ;-) ?
https://htmlpreview.github.io/?https://github.com/MrYsLab/pymata-express/blob/master/html/pymata_express/index.html#pymata_express.pymata_express.PymataExpress.set_pin_mode_servo

**Comment by MrYsLab** [comment]
@lejbxl Thanks - you are correct. The comment should have stated microseconds and not milliseconds. I will update the API documentation and source code but will not publish a new release with these changes since they do not affect the actual operation of the code.
The Pymata family of APIs is now in maintenance mode, and only operational bug fixes will result in a new release. 
In place of the pymata family of APIs, you may wish to check out [Telemetrix](https://mryslab.github.io/telemetrix/). It is actively in development and supports many more features than Firmata. Also, it uses a simplified 8-bit communication protocol instead of the 7-bit scheme employed by Firmata. You can view its API [here](https://htmlpreview.github.io/?https://github.com/MrYsLab/telemetrix/blob/master/html/telemetrix/index.html). The async API may be found [here](https://htmlpreview.github.io/?https://github.com/MrYsLab/telemetrix-aio/blob/master/html/telemetrix_aio/index.html).
