### ISSUE TITLE
Difference between digital_output & digital_pin_ouput

### ISSUE THREAD

**Issue by wlwatkins** [MrYsLab/pymata-express#7]
Hi, me again, 
I'm back working on my little robot and had a question regarding the difference between digital_output & digital_pin_ouput. 
If you have time, you should detail the example page 
[https://mryslab.github.io/pymata-express/examples/](https://mryslab.github.io/pymata-express/examples/)
detailing the different commands. I know it's quite some work, but looking at the api is not enough to understand the difference between these two option for instance. 

Thanks in advance

W

**Comment by MrYsLab** [comment]
Hi Will,
    Thanks for your input on the documentation. First, in case the differences between digital_ouput and digital_pin_output are still unclear, digital_output was the original way that Firmata set a digital pin's output. If you look at the code to do this on the [pymata-express side](https://github.com/MrYsLab/pymata-express/blob/0db412f279b9ae1c161325aa43a64be78a562699/pymata_express/pymata_express.py#L487),  you will see there is quite a lot of bit twiddling going on. If you compare that with [digital_pin_output](https://github.com/MrYsLab/pymata-express/blob/0db412f279b9ae1c161325aa43a64be78a562699/pymata_express/pymata_express.py#L473), digital_pin_output is much more efficient. Ultimately, the result is the same, but one executes faster than the other. The digital_pin_output command was added to Firmata within the last few years.

As to rewriting the documentation, I am unlikely to do so, since it would mean that I would be essentially documenting Firmata and that is something that the Firmata maintainer should do. 

What I would suggest, is first, when in doubt about a command, check the source code, The [API documentation](http://htmlpreview.github.io/?https://github.com/MrYsLab/pymata-express/blob/master/documentation/api/pymata_express.html) will allow you to easily look at the code. Just click on the "SOURCE CODE" link for any of the methods to expose the source code. If things are still unclear, please feel free to contact me either here on GitHub, by email (my address is listed [here](https://github.com/MrYsLab)).

I am going to close this issue, but please feel free to leave any addtional comments here and I will see them.
